[package]
name = "rusttest"
version = "0.1.0"
edition = "2021"
authors = ["Mika Herrmann <mika.herrmann@js-soft.com>"]

[lib]
name = "rust_test"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]